import { jsPDF } from 'jspdf'
import { BUDGET_CATEGORIES } from '../types/budget'
import type { TravelGuideData } from '../types/travelGuide'
import { BRAND_NAME, BRAND_TAGLINE } from '../constants/brand'
import { formatCurrency } from '../utils/formatCurrency'
import { PDF } from './theme'
import {
  addPageFooters,
  drawPageHeader,
  ensureSpace,
  formatGuideDate,
  formatShortDate,
  setFill,
  setText,
  wrapText,
  type PdfCursor,
} from './pdfLayout'
import { drawAccentBar, drawIcon, drawSectionRule, type GuideIcon } from './pdfIcons'

function drawCoverPage(doc: jsPDF, data: TravelGuideData) {
  setFill(doc, PDF.ink)
  doc.rect(0, 0, PDF.pageWidth, PDF.pageHeight, 'F')

  setFill(doc, PDF.brass)
  doc.rect(PDF.margin, 42, PDF.contentWidth, 1.5, 'F')
  doc.rect(PDF.margin, PDF.pageHeight - 52, PDF.contentWidth * 0.55, 0.8, 'F')

  doc.setFont(PDF.fontMono, 'normal')
  doc.setFontSize(10)
  setText(doc, PDF.brass)
  doc.text(BRAND_NAME.toUpperCase(), PDF.margin, 52)

  doc.setFont(PDF.fontDisplay, 'bold')
  doc.setFontSize(36)
  setText(doc, PDF.parchment)
  doc.text(data.destinationName, PDF.margin, 78)

  doc.setFont(PDF.fontDisplay, 'italic')
  doc.setFontSize(14)
  setText(doc, PDF.parchment)
  doc.text(data.country, PDF.margin, 90)

  const taglineLines = doc.splitTextToSize(data.tagline, PDF.contentWidth) as string[]
  doc.setFont(PDF.fontBody, 'normal')
  doc.setFontSize(12)
  taglineLines.forEach((line, index) => {
    doc.text(line, PDF.margin, 104 + index * 6)
  })

  doc.setFont(PDF.fontMono, 'normal')
  doc.setFontSize(9)
  setText(doc, PDF.brass)
  doc.text('YOUR PERSONAL TRAVEL GUIDE', PDF.margin, 132)

  doc.setFont(PDF.fontBody, 'normal')
  doc.setFontSize(10)
  setText(doc, PDF.parchment)
  doc.text(formatGuideDate(data.generatedAt), PDF.margin, 142)
  doc.text(BRAND_TAGLINE, PDF.margin, PDF.pageHeight - 38)

  doc.setFont(PDF.fontMono, 'normal')
  doc.setFontSize(8)
  setText(doc, PDF.muted)
  doc.text('Premium edition · Generated by Waymark', PDF.margin, PDF.pageHeight - 28)
}

function drawSectionTitle(
  doc: jsPDF,
  cursor: PdfCursor,
  icon: GuideIcon,
  title: string,
  subtitle?: string,
) {
  ensureSpace(doc, cursor, 24)
  drawIcon(doc, icon, PDF.margin, cursor.y - 2)
  doc.setFont(PDF.fontDisplay, 'bold')
  doc.setFontSize(18)
  setText(doc, PDF.ink)
  doc.text(title, PDF.margin + 12, cursor.y + 5)
  cursor.y += 12

  if (subtitle) {
    doc.setFont(PDF.fontBody, 'normal')
    doc.setFontSize(10)
    setText(doc, PDF.muted)
    cursor.y = wrapText(doc, subtitle, PDF.margin, cursor.y, PDF.contentWidth, 5) + 2
  }

  drawSectionRule(doc, cursor.y)
  cursor.y += 10
}

function drawBullet(
  doc: jsPDF,
  cursor: PdfCursor,
  text: string,
  indent = 0,
) {
  ensureSpace(doc, cursor, 12)
  setFill(doc, PDF.teal)
  doc.circle(PDF.margin + 2 + indent, cursor.y - 1.5, 1, 'F')
  doc.setFont(PDF.fontBody, 'normal')
  doc.setFontSize(10)
  setText(doc, PDF.ink)
  cursor.y = wrapText(doc, text, PDF.margin + 8 + indent, cursor.y, PDF.contentWidth - 8 - indent, 5) + 3
}

function drawSummaryPage(doc: jsPDF, data: TravelGuideData, cursor: PdfCursor) {
  doc.addPage()
  cursor.y = PDF.margin + 4
  drawPageHeader(doc, cursor)

  drawSectionTitle(
    doc,
    cursor,
    'summary',
    'Trip Summary',
    `A curated overview of your ${data.tripLength}-day journey to ${data.destinationName}.`,
  )

  const stats = [
    ['Destination', `${data.destinationName}, ${data.country}`],
    ['Duration', `${data.tripLength} days`],
    ['Activities planned', String(data.activityCount)],
    ['Hotel reservations', String(data.reservationCount)],
    ['Estimated budget', formatCurrency(data.budgetTotal)],
    ['Budget limit', formatCurrency(data.budgetLimit)],
    ['AI highlights', String(data.aiPlaces.length)],
    ['Generated', formatGuideDate(data.generatedAt)],
  ]

  stats.forEach(([label, value]) => {
    ensureSpace(doc, cursor, 14)
    drawAccentBar(doc, PDF.margin, cursor.y - 4, 10)
    doc.setFont(PDF.fontMono, 'normal')
    doc.setFontSize(8)
    setText(doc, PDF.teal)
    doc.text(label.toUpperCase(), PDF.margin + 6, cursor.y)
    doc.setFont(PDF.fontBody, 'normal')
    doc.setFontSize(11)
    setText(doc, PDF.ink)
    doc.text(value, PDF.margin + 6, cursor.y + 6)
    cursor.y += 16
  })

  if (data.aiPlaces.length > 0) {
    ensureSpace(doc, cursor, 20)
    doc.setFont(PDF.fontDisplay, 'bold')
    doc.setFontSize(12)
    setText(doc, PDF.ink)
    doc.text('Featured stops', PDF.margin, cursor.y)
    cursor.y += 8

    for (const place of data.aiPlaces.slice(0, 5)) {
      drawBullet(doc, cursor, `${place.name} — ${place.description}`)
    }
  }
}

function drawItineraryPages(doc: jsPDF, data: TravelGuideData, cursor: PdfCursor) {
  doc.addPage()
  cursor.y = PDF.margin + 4
  drawPageHeader(doc, cursor)

  drawSectionTitle(
    doc,
    cursor,
    'itinerary',
    'Daily Itinerary',
    'Your day-by-day plan with times and notes.',
  )

  for (let day = 1; day <= data.tripLength; day += 1) {
    const items = data.activitiesByDay[day] ?? []
    ensureSpace(doc, cursor, 20)

    setFill(doc, PDF.ink)
    doc.roundedRect(PDF.margin, cursor.y - 5, PDF.contentWidth, 10, 2, 2, 'F')
    doc.setFont(PDF.fontMono, 'bold')
    doc.setFontSize(10)
    setText(doc, PDF.parchment)
    doc.text(`DAY ${day}`, PDF.margin + 4, cursor.y + 1.5)
    cursor.y += 12

    if (items.length === 0) {
      doc.setFont(PDF.fontBody, 'italic')
      doc.setFontSize(10)
      setText(doc, PDF.muted)
      doc.text('No activities scheduled — add plans in Waymark.', PDF.margin + 4, cursor.y)
      cursor.y += 10
      continue
    }

    for (const activity of items) {
      ensureSpace(doc, cursor, 18)
      const timeLabel = activity.time ? `${activity.time} · ` : ''
      doc.setFont(PDF.fontBody, 'bold')
      doc.setFontSize(11)
      setText(doc, PDF.ink)
      doc.text(`${timeLabel}${activity.title}`, PDF.margin + 4, cursor.y)
      cursor.y += 5

      if (activity.notes) {
        doc.setFont(PDF.fontBody, 'normal')
        doc.setFontSize(9)
        setText(doc, PDF.muted)
        cursor.y = wrapText(doc, activity.notes, PDF.margin + 4, cursor.y, PDF.contentWidth - 8, 4.5) + 4
      } else {
        cursor.y += 4
      }
    }

    cursor.y += 4
  }
}

function drawBudgetPage(doc: jsPDF, data: TravelGuideData, cursor: PdfCursor) {
  doc.addPage()
  cursor.y = PDF.margin + 4
  drawPageHeader(doc, cursor)

  drawSectionTitle(
    doc,
    cursor,
    'budget',
    'Budget Overview',
    `Total estimate ${formatCurrency(data.budgetTotal)} against a ${formatCurrency(data.budgetLimit)} limit.`,
  )

  const barMaxWidth = PDF.contentWidth - 50
  let maxAmount = 0
  for (const category of BUDGET_CATEGORIES) {
    maxAmount = Math.max(maxAmount, data.budget[category.id])
  }

  for (const category of BUDGET_CATEGORIES) {
    const amount = data.budget[category.id]
    const share = data.budgetTotal > 0 ? amount / data.budgetTotal : 0
    ensureSpace(doc, cursor, 16)

    doc.setFont(PDF.fontBody, 'normal')
    doc.setFontSize(10)
    setText(doc, PDF.ink)
    doc.text(category.label, PDF.margin, cursor.y)

    doc.setFont(PDF.fontMono, 'normal')
    doc.text(formatCurrency(amount), PDF.pageWidth - PDF.margin, cursor.y, {
      align: 'right',
    })

    const barWidth = maxAmount > 0 ? (amount / maxAmount) * barMaxWidth : 0
    setFill(doc, PDF.parchment)
    doc.roundedRect(PDF.margin, cursor.y + 2, barMaxWidth, 4, 1, 1, 'F')

    const rgb = hexToRgb(category.color)
    doc.setFillColor(rgb[0], rgb[1], rgb[2])
    doc.roundedRect(PDF.margin, cursor.y + 2, barWidth, 4, 1, 1, 'F')

    doc.setFont(PDF.fontMono, 'normal')
    doc.setFontSize(8)
    setText(doc, PDF.muted)
    doc.text(`${Math.round(share * 100)}% of total`, PDF.margin, cursor.y + 10)
    cursor.y += 16
  }

  ensureSpace(doc, cursor, 20)
  const over = data.budgetTotal - data.budgetLimit
  setFill(doc, over > 0 ? PDF.rust : PDF.teal)
  doc.roundedRect(PDF.margin, cursor.y, PDF.contentWidth, 14, 2, 2, 'F')
  doc.setFont(PDF.fontBody, 'bold')
  doc.setFontSize(11)
  setText(doc, PDF.parchment)
  const status =
    over > 0
      ? `${formatCurrency(over)} over budget limit`
      : `${formatCurrency(Math.abs(over))} under budget limit`
  doc.text(status, PDF.margin + 4, cursor.y + 9)
  cursor.y += 20
}

function drawWeatherPage(doc: jsPDF, data: TravelGuideData, cursor: PdfCursor) {
  doc.addPage()
  cursor.y = PDF.margin + 4
  drawPageHeader(doc, cursor)

  drawSectionTitle(
    doc,
    cursor,
    'weather',
    'Weather Forecast',
    data.weather
      ? 'Five-day outlook from Open-Meteo for your destination.'
      : 'Weather data unavailable — check Waymark before departure.',
  )

  if (!data.weather) return

  ensureSpace(doc, cursor, 22)
  setFill(doc, PDF.ink)
  doc.roundedRect(PDF.margin, cursor.y, PDF.contentWidth, 18, 2, 2, 'F')
  doc.setFont(PDF.fontDisplay, 'bold')
  doc.setFontSize(22)
  setText(doc, PDF.parchment)
  doc.text(`${data.weather.currentTemp}°C`, PDF.margin + 6, cursor.y + 11)
  doc.setFont(PDF.fontBody, 'normal')
  doc.setFontSize(11)
  doc.text(data.weather.currentCondition, PDF.margin + 40, cursor.y + 11)
  cursor.y += 26

  for (const day of data.weather.daily) {
    ensureSpace(doc, cursor, 14)
    setFill(doc, PDF.parchment)
    doc.roundedRect(PDF.margin, cursor.y - 4, PDF.contentWidth, 12, 2, 2, 'F')

    doc.setFont(PDF.fontBody, 'bold')
    doc.setFontSize(10)
    setText(doc, PDF.ink)
    doc.text(formatShortDate(day.date), PDF.margin + 4, cursor.y + 3)

    doc.setFont(PDF.fontBody, 'normal')
    doc.text(day.condition, PDF.margin + 36, cursor.y + 3)

    doc.setFont(PDF.fontMono, 'normal')
    doc.text(
      `${day.tempMin}° – ${day.tempMax}°C`,
      PDF.pageWidth - PDF.margin - 4,
      cursor.y + 3,
      { align: 'right' },
    )
    cursor.y += 14
  }
}

function drawPackingPage(doc: jsPDF, data: TravelGuideData, cursor: PdfCursor) {
  doc.addPage()
  cursor.y = PDF.margin + 4
  drawPageHeader(doc, cursor)

  drawSectionTitle(
    doc,
    cursor,
    'packing',
    'Packing List',
    data.packingGroups.length > 0
      ? 'Items from your AI packing checklist.'
      : 'Generate a packing list in Waymark to include it here.',
  )

  if (data.packingGroups.length === 0) return

  for (const group of data.packingGroups) {
    ensureSpace(doc, cursor, 16)
    doc.setFont(PDF.fontDisplay, 'bold')
    doc.setFontSize(12)
    setText(doc, PDF.ink)
    doc.text(group.label, PDF.margin, cursor.y)
    cursor.y += 7

    for (const item of group.items) {
      const mark = item.checked ? '[x]' : '[ ]'
      drawBullet(doc, cursor, `${mark} ${item.label}`, 4)
    }
    cursor.y += 4
  }
}

function drawHotelsPage(doc: jsPDF, data: TravelGuideData, cursor: PdfCursor) {
  doc.addPage()
  cursor.y = PDF.margin + 4
  drawPageHeader(doc, cursor)

  drawSectionTitle(
    doc,
    cursor,
    'hotel',
    'Hotels & Stays',
    'Confirmed reservations and check-in details.',
  )

  if (data.reservations.length === 0) {
    doc.setFont(PDF.fontBody, 'italic')
    doc.setFontSize(10)
    setText(doc, PDF.muted)
    doc.text('No hotel reservations yet.', PDF.margin, cursor.y)
    return
  }

  for (const stay of data.reservations) {
    ensureSpace(doc, cursor, 28)
    setFill(doc, PDF.parchment)
    doc.roundedRect(PDF.margin, cursor.y - 4, PDF.contentWidth, 24, 2, 2, 'F')

    drawIcon(doc, 'hotel', PDF.margin + 4, cursor.y, 7)

    doc.setFont(PDF.fontDisplay, 'bold')
    doc.setFontSize(12)
    setText(doc, PDF.ink)
    doc.text(stay.hotelName, PDF.margin + 16, cursor.y + 4)

    doc.setFont(PDF.fontBody, 'normal')
    doc.setFontSize(10)
    setText(doc, PDF.muted)
    doc.text(stay.destinationName, PDF.margin + 16, cursor.y + 10)

    doc.setFont(PDF.fontMono, 'normal')
    doc.setFontSize(9)
    setText(doc, PDF.ink)
    doc.text(
      `Check-in ${stay.checkIn}  →  Check-out ${stay.checkOut}`,
      PDF.margin + 16,
      cursor.y + 16,
    )
    doc.text(
      `${formatCurrency(stay.pricePerNight)} / night`,
      PDF.pageWidth - PDF.margin - 4,
      cursor.y + 16,
      { align: 'right' },
    )
    cursor.y += 28
  }
}

function drawEmergencyPage(doc: jsPDF, data: TravelGuideData, cursor: PdfCursor) {
  doc.addPage()
  cursor.y = PDF.margin + 4
  drawPageHeader(doc, cursor)

  drawSectionTitle(
    doc,
    cursor,
    'emergency',
    'Emergency Contacts',
    `Important numbers and contacts for ${data.country}.`,
  )

  for (const contact of data.emergencyContacts) {
    ensureSpace(doc, cursor, 20)
    drawIcon(doc, contact.icon, PDF.margin, cursor.y - 2, 7)

    doc.setFont(PDF.fontMono, 'normal')
    doc.setFontSize(8)
    setText(doc, PDF.teal)
    doc.text(contact.label.toUpperCase(), PDF.margin + 12, cursor.y + 1)

    doc.setFont(PDF.fontBody, 'bold')
    doc.setFontSize(11)
    setText(doc, PDF.ink)
    cursor.y = wrapText(doc, contact.value, PDF.margin + 12, cursor.y + 7, PDF.contentWidth - 14, 5) + 6
  }
}

function drawTipsPage(doc: jsPDF, data: TravelGuideData, cursor: PdfCursor) {
  doc.addPage()
  cursor.y = PDF.margin + 4
  drawPageHeader(doc, cursor)

  drawSectionTitle(
    doc,
    cursor,
    'tips',
    'Travel Tips',
    'Expert advice tailored to your destination and plans.',
  )

  data.travelTips.forEach((tip, index) => {
    ensureSpace(doc, cursor, 14)
    doc.setFont(PDF.fontMono, 'bold')
    doc.setFontSize(9)
    setText(doc, PDF.brass)
    doc.text(String(index + 1).padStart(2, '0'), PDF.margin, cursor.y)
    doc.setFont(PDF.fontBody, 'normal')
    doc.setFontSize(10)
    setText(doc, PDF.ink)
    cursor.y = wrapText(doc, tip, PDF.margin + 10, cursor.y, PDF.contentWidth - 12, 5) + 5
  })
}

function hexToRgb(hex: string): [number, number, number] {
  const normalized = hex.replace('#', '')
  const value = Number.parseInt(normalized, 16)
  return [(value >> 16) & 255, (value >> 8) & 255, value & 255]
}

export function buildTravelGuidePdf(data: TravelGuideData): jsPDF {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', compress: true })
  const cursor: PdfCursor = { y: PDF.margin }

  drawCoverPage(doc, data)
  drawSummaryPage(doc, data, cursor)
  drawItineraryPages(doc, data, cursor)
  drawBudgetPage(doc, data, cursor)
  drawWeatherPage(doc, data, cursor)
  drawPackingPage(doc, data, cursor)
  drawHotelsPage(doc, data, cursor)
  drawEmergencyPage(doc, data, cursor)
  drawTipsPage(doc, data, cursor)

  addPageFooters(doc, true)
  return doc
}

export function downloadTravelGuidePdf(data: TravelGuideData): void {
  const doc = buildTravelGuidePdf(data)
  const slug = data.destinationName.toLowerCase().replace(/\s+/g, '-')
  doc.save(`waymark-travel-guide-${slug}.pdf`)
}
